# Form implementation generated from reading ui file 'D:\KTLT\HotelManagement\ui\HomePageMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1097, 775)
        MainWindow.setWindowOpacity(2.0)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-6, -5, 1101, 721))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\KTLT\\HotelManagement\\ui\\../images/homepage.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButtonAboutUs = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonAboutUs.setGeometry(QtCore.QRect(20, 440, 161, 61))
        self.pushButtonAboutUs.setStyleSheet("\n"
"background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 63 14pt \"Sitka Heading Semibold\";\n"
"")
        self.pushButtonAboutUs.setObjectName("pushButtonAboutUs")
        self.pushButtonLogIn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLogIn.setGeometry(QtCore.QRect(10, 500, 181, 41))
        self.pushButtonLogIn.setStyleSheet("\n"
"background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 63 14pt \"Sitka Heading Semibold\";")
        self.pushButtonLogIn.setObjectName("pushButtonLogIn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1097, 26))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(parent=self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuSystem = QtWidgets.QMenu(parent=self.menubar)
        self.menuSystem.setObjectName("menuSystem")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_data = QtGui.QAction(parent=MainWindow)
        self.actionImport_data.setObjectName("actionImport_data")
        self.actionExport_data = QtGui.QAction(parent=MainWindow)
        self.actionExport_data.setObjectName("actionExport_data")
        self.menuSystem.addSeparator()
        self.menuSystem.addSeparator()
        self.menuSystem.addAction(self.actionImport_data)
        self.menuSystem.addAction(self.actionExport_data)
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuSystem.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonAboutUs.setText(_translate("MainWindow", "About Us"))
        self.pushButtonLogIn.setText(_translate("MainWindow", "Log In"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuSystem.setTitle(_translate("MainWindow", "System"))
        self.actionImport_data.setText(_translate("MainWindow", "Import data"))
        self.actionExport_data.setText(_translate("MainWindow", "Export data"))
