# Form implementation generated from reading ui file 'D:\KTLT\HotelManagement\ui\MainWindowManagement.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 780)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 780))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 780))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 180, 1281, 601))
        self.tabWidget.setStyleSheet("font: 57 14pt \"SFU Toledo\";")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.groupBox = QtWidgets.QGroupBox(parent=self.tab_8)
        self.groupBox.setGeometry(QtCore.QRect(530, 10, 741, 461))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 SFU Toledo Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.221636, y1:0.171091, x2:0.994318, y2:0.960227, stop:0.0681818 rgba(80, 11, 40, 255), stop:1 rgba(211, 26, 48, 243));\n"
"font: 75 12pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(255, 232, 137);\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.groupBox)
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"color: rgb(0, 0, 0);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(119, 139, 206))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(119, 139, 206))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(119, 139, 206))
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(119, 139, 206))
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(119, 139, 206))
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.label_2 = QtWidgets.QLabel(parent=self.tab_8)
        self.label_2.setGeometry(QtCore.QRect(910, -10, 421, 31))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.groupBoxCustomerDetails = QtWidgets.QGroupBox(parent=self.tab_8)
        self.groupBoxCustomerDetails.setGeometry(QtCore.QRect(10, 10, 511, 461))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 SFU Toledo Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBoxCustomerDetails.setFont(font)
        self.groupBoxCustomerDetails.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"color: qlineargradient(spread:pad, x1:0.608, y1:0.546091, x2:0.994318, y2:0.960227, stop:0.0681818 rgba(80, 11, 40, 255), stop:1 rgba(210, 26, 48, 243));\n"
"font: 12pt \"#9Slide03 SFU Toledo Bold\";\n"
"    border: 1px solid rgb(60, 60, 60); /* Viền đen */\n"
"    border-radius: 1px; /* Bo góc nhẹ để nhìn mềm mại hơn */\n"
"hover {\n"
"    background-color: rgb(90, 150, 200); /* Màu sáng hơn khi hover */\n"
"}\n"
"")
        self.groupBoxCustomerDetails.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.groupBoxCustomerDetails.setFlat(False)
        self.groupBoxCustomerDetails.setObjectName("groupBoxCustomerDetails")
        self.label_168 = QtWidgets.QLabel(parent=self.groupBoxCustomerDetails)
        self.label_168.setGeometry(QtCore.QRect(10, 80, 121, 31))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 SFU Toledo Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_168.setFont(font)
        self.label_168.setStyleSheet("background-color: transparent;\n"
" border:transparent;")
        self.label_168.setObjectName("label_168")
        self.label_169 = QtWidgets.QLabel(parent=self.groupBoxCustomerDetails)
        self.label_169.setGeometry(QtCore.QRect(10, 130, 151, 31))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 SFU Toledo Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_169.setFont(font)
        self.label_169.setStyleSheet("background-color: transparent; border:transparent;")
        self.label_169.setObjectName("label_169")
        self.label_170 = QtWidgets.QLabel(parent=self.groupBoxCustomerDetails)
        self.label_170.setGeometry(QtCore.QRect(10, 180, 151, 31))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 SFU Toledo Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_170.setFont(font)
        self.label_170.setStyleSheet("background-color: transparent; border:transparent;")
        self.label_170.setObjectName("label_170")
        self.label_171 = QtWidgets.QLabel(parent=self.groupBoxCustomerDetails)
        self.label_171.setGeometry(QtCore.QRect(10, 230, 151, 31))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 SFU Toledo Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_171.setFont(font)
        self.label_171.setStyleSheet("background-color: transparent; border:transparent;")
        self.label_171.setObjectName("label_171")
        self.label_172 = QtWidgets.QLabel(parent=self.groupBoxCustomerDetails)
        self.label_172.setGeometry(QtCore.QRect(10, 280, 191, 31))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 SFU Toledo Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_172.setFont(font)
        self.label_172.setStyleSheet("background-color: transparent; border:transparent;")
        self.label_172.setObjectName("label_172")
        self.label_173 = QtWidgets.QLabel(parent=self.groupBoxCustomerDetails)
        self.label_173.setGeometry(QtCore.QRect(10, 330, 191, 31))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 SFU Toledo Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_173.setFont(font)
        self.label_173.setStyleSheet("background-color: transparent; border:transparent;")
        self.label_173.setObjectName("label_173")
        self.pushButtonUpdate = QtWidgets.QPushButton(parent=self.groupBoxCustomerDetails)
        self.pushButtonUpdate.setGeometry(QtCore.QRect(30, 400, 91, 51))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 SFU Toledo Bold")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonUpdate.setFont(font)
        self.pushButtonUpdate.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.221636, y1:0.171091, x2:0.994318, y2:0.960227,\n"
"                                      stop:0.0681818 rgba(80, 11, 40, 255),\n"
"                                      stop:1 rgba(211, 26, 48, 243)); /* Gradient màu nền */\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"\n"
"    /* Viền sáng ở trên & tối ở dưới để tạo hiệu ứng 3D */\n"
"    border: 2px solid rgb(255, 255, 255); /* Viền trắng tổng thể */\n"
"    border-top: 3px solid rgb(255, 255, 255); /* Viền trên sáng hơn */\n"
"    border-left: 3px solid rgb(255, 255, 255);\n"
"    border-bottom: 3px solid rgb(150, 0, 20); /* Viền dưới tối hơn */\n"
"    border-right: 3px solid rgb(150, 0, 20);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-top: 3px solid rgb(150, 0, 20); /* Khi nhấn, đổi viền trên tối hơn */\n"
"    border-left: 3px solid rgb(150, 0, 20);\n"
"    border-bottom: 3px solid rgb(255, 255, 255); /* Viền dưới sáng hơn */\n"
"    border-right: 3px solid rgb(255, 255, 255);\n"
"    background-color: rgb(150, 0, 20); /* Màu nền tối hơn khi nhấn */\n"
"}\n"
"")
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        self.pushButtonDelete = QtWidgets.QPushButton(parent=self.groupBoxCustomerDetails)
        self.pushButtonDelete.setGeometry(QtCore.QRect(180, 400, 91, 51))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 SFU Toledo Bold")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonDelete.setFont(font)
        self.pushButtonDelete.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.221636, y1:0.171091, x2:0.994318, y2:0.960227,\n"
"                                      stop:0.0681818 rgba(80, 11, 40, 255),\n"
"                                      stop:1 rgba(211, 26, 48, 243)); /* Gradient màu nền */\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"\n"
"    /* Viền sáng ở trên & tối ở dưới để tạo hiệu ứng 3D */\n"
"    border: 2px solid rgb(255, 255, 255); /* Viền trắng tổng thể */\n"
"    border-top: 3px solid rgb(255, 255, 255); /* Viền trên sáng hơn */\n"
"    border-left: 3px solid rgb(255, 255, 255);\n"
"    border-bottom: 3px solid rgb(150, 0, 20); /* Viền dưới tối hơn */\n"
"    border-right: 3px solid rgb(150, 0, 20);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-top: 3px solid rgb(150, 0, 20); /* Khi nhấn, đổi viền trên tối hơn */\n"
"    border-left: 3px solid rgb(150, 0, 20);\n"
"    border-bottom: 3px solid rgb(255, 255, 255); /* Viền dưới sáng hơn */\n"
"    border-right: 3px solid rgb(255, 255, 255);\n"
"    background-color: rgb(150, 0, 20); /* Màu nền tối hơn khi nhấn */\n"
"}\n"
"")
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.pushButtonreset = QtWidgets.QPushButton(parent=self.groupBoxCustomerDetails)
        self.pushButtonreset.setGeometry(QtCore.QRect(330, 400, 101, 51))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 SFU Toledo Bold")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonreset.setFont(font)
        self.pushButtonreset.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.221636, y1:0.171091, x2:0.994318, y2:0.960227,\n"
"                                      stop:0.0681818 rgba(80, 11, 40, 255),\n"
"                                      stop:1 rgba(211, 26, 48, 243)); /* Gradient màu nền */\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"\n"
"    /* Viền sáng ở trên & tối ở dưới để tạo hiệu ứng 3D */\n"
"    border: 2px solid rgb(255, 255, 255); /* Viền trắng tổng thể */\n"
"    border-top: 3px solid rgb(255, 255, 255); /* Viền trên sáng hơn */\n"
"    border-left: 3px solid rgb(255, 255, 255);\n"
"    border-bottom: 3px solid rgb(150, 0, 20); /* Viền dưới tối hơn */\n"
"    border-right: 3px solid rgb(150, 0, 20);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-top: 3px solid rgb(150, 0, 20); /* Khi nhấn, đổi viền trên tối hơn */\n"
"    border-left: 3px solid rgb(150, 0, 20);\n"
"    border-bottom: 3px solid rgb(255, 255, 255); /* Viền dưới sáng hơn */\n"
"    border-right: 3px solid rgb(255, 255, 255);\n"
"    background-color: rgb(150, 0, 20); /* Màu nền tối hơn khi nhấn */\n"
"}\n"
"")
        self.pushButtonreset.setObjectName("pushButtonreset")
        self.label_174 = QtWidgets.QLabel(parent=self.groupBoxCustomerDetails)
        self.label_174.setGeometry(QtCore.QRect(170, 30, 321, 351))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 SFU Toledo Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_174.setFont(font)
        self.label_174.setStyleSheet("QWidget {\n"
"    background-color: transparent; /* Nền hoàn toàn trong suốt */\n"
"    border: 2px solid transparent; /* Viền trong suốt */\n"
"    color: rgba(255, 255, 255, 255); /* Giữ màu chữ */\n"
"    font: 10pt \"#9Slide03 SFU Toledo Bold\";\n"
"    border-radius: 2px; /* Bo góc nhẹ */\n"
"}\n"
"\n"
"QWidget:hover {\n"
"    background-color: rgba(90, 150, 200, 100); /* Hover có màu mờ (gần trong suốt) */\n"
"}\n"
"")
        self.label_174.setText("")
        self.label_174.setPixmap(QtGui.QPixmap("D:\\KTLT\\HotelManagement\\ui\\../images/booking.jpg"))
        self.label_174.setScaledContents(True)
        self.label_174.setObjectName("label_174")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.groupBoxCustomerDetails)
        self.lineEdit.setGeometry(QtCore.QRect(190, 40, 281, 31))
        self.lineEdit.setStyleSheet("border: 2px solid transparent;\n"
"background-color: rgb(255, 255, 255,200);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox_3 = QtWidgets.QComboBox(parent=self.groupBoxCustomerDetails)
        self.comboBox_3.setGeometry(QtCore.QRect(190, 280, 281, 31))
        self.comboBox_3.setStyleSheet("border: 2px solid transparent;\n"
"background-color: rgb(255, 255, 255,200);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.groupBoxCustomerDetails)
        self.lineEdit_3.setGeometry(QtCore.QRect(190, 90, 281, 31))
        self.lineEdit_3.setStyleSheet("border: 2px solid transparent;\n"
"background-color: rgb(255, 255, 255,200);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_175 = QtWidgets.QLabel(parent=self.groupBoxCustomerDetails)
        self.label_175.setGeometry(QtCore.QRect(10, 30, 121, 41))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 SFU Toledo Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_175.setFont(font)
        self.label_175.setStyleSheet("background-color: transparent;\n"
" border:transparent;")
        self.label_175.setObjectName("label_175")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.groupBoxCustomerDetails)
        self.lineEdit_4.setGeometry(QtCore.QRect(190, 330, 281, 31))
        self.lineEdit_4.setStyleSheet("border: 2px solid transparent;\n"
"background-color: rgb(255, 255, 255,200);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.groupBoxCustomerDetails)
        self.lineEdit_5.setGeometry(QtCore.QRect(190, 130, 281, 31))
        self.lineEdit_5.setStyleSheet("border: 2px solid transparent;\n"
"background-color: rgb(255, 255, 255,200);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.groupBoxCustomerDetails)
        self.lineEdit_6.setGeometry(QtCore.QRect(190, 180, 281, 31))
        self.lineEdit_6.setStyleSheet("border: 2px solid transparent;\n"
"background-color: rgb(255, 255, 255,200);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.groupBoxCustomerDetails)
        self.lineEdit_7.setGeometry(QtCore.QRect(190, 230, 281, 31))
        self.lineEdit_7.setStyleSheet("border: 2px solid transparent;\n"
"background-color: rgb(255, 255, 255,200);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.tabWidget.addTab(self.tab_8, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.pushButton_exit = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_exit.setGeometry(QtCore.QRect(750, 450, 131, 51))
        self.pushButton_exit.setStyleSheet("border-radius: 15px;\n"
"font: 75 15pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(255, 232, 137);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.527363 rgba(80, 11, 40, 255), stop:1 rgba(187, 23, 43, 255));\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\KTLT\\HotelManagement\\ui\\../../TranHieuKieuDuyen_K244111457_K24411E/Midterm_TranHieuKieuDuyen/WarehouseManagement/images/close.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_exit.setIcon(icon)
        self.pushButton_exit.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_checkout = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_checkout.setGeometry(QtCore.QRect(570, 450, 151, 51))
        self.pushButton_checkout.setStyleSheet("border-radius: 15px;\n"
"font: 75 15pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(255, 232, 137);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.527363 rgba(80, 11, 40, 255), stop:1 rgba(187, 23, 43, 255));\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\KTLT\\HotelManagement\\ui\\../../Downloads/187510.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_checkout.setIcon(icon1)
        self.pushButton_checkout.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_checkout.setObjectName("pushButton_checkout")
        self.tableWidget_Room = QtWidgets.QTableWidget(parent=self.widget)
        self.tableWidget_Room.setGeometry(QtCore.QRect(10, 100, 1251, 331))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_Room.sizePolicy().hasHeightForWidth())
        self.tableWidget_Room.setSizePolicy(sizePolicy)
        self.tableWidget_Room.setMaximumSize(QtCore.QSize(16777215, 411))
        self.tableWidget_Room.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.733, x2:0.51194, y2:0.744, stop:0.457711 rgba(245, 247, 250, 255), stop:1 rgba(195, 207, 226, 255));\n"
"")
        self.tableWidget_Room.setObjectName("tableWidget_Room")
        self.tableWidget_Room.setColumnCount(4)
        self.tableWidget_Room.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Room.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Room.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Room.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Room.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Room.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Room.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Room.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Room.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Room.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Room.setHorizontalHeaderItem(3, item)
        self.dateEdit_date = QtWidgets.QDateEdit(parent=self.widget)
        self.dateEdit_date.setGeometry(QtCore.QRect(990, 40, 271, 31))
        self.dateEdit_date.setDateTime(QtCore.QDateTime(QtCore.QDate(1999, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_date.setObjectName("dateEdit_date")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(890, 30, 81, 31))
        self.label.setStyleSheet("font: 75 20pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(0, 0, 0);\n"
"\n"
"")
        self.label.setObjectName("label")
        self.pushButton_checkin = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_checkin.setGeometry(QtCore.QRect(410, 450, 141, 51))
        self.pushButton_checkin.setStyleSheet("border-radius: 15px;\n"
"font: 75 15pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(255, 232, 137);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.527363 rgba(80, 11, 40, 255), stop:1 rgba(187, 23, 43, 255));\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\KTLT\\HotelManagement\\ui\\../../Downloads/Tick.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_checkin.setIcon(icon2)
        self.pushButton_checkin.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_checkin.setObjectName("pushButton_checkin")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.widget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 581, 81))
        font = QtGui.QFont()
        font.setFamily("SFU Toledo")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_booked = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButton_booked.setGeometry(QtCore.QRect(120, 40, 91, 31))
        self.pushButton_booked.setStyleSheet("border-radius: 15px;\n"
"border-radius: 15px;\n"
"font: 75 15pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(255, 232, 137);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.527363 rgba(80, 11, 40, 255), stop:1 rgba(187, 23, 43, 255));")
        self.pushButton_booked.setObjectName("pushButton_booked")
        self.pushButton_vacant = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButton_vacant.setGeometry(QtCore.QRect(230, 40, 101, 31))
        self.pushButton_vacant.setStyleSheet("border-radius: 15px;\n"
"font: 75 15pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(255, 232, 137);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.527363 rgba(80, 11, 40, 255), stop:1 rgba(187, 23, 43, 255));")
        self.pushButton_vacant.setObjectName("pushButton_vacant")
        self.pushButton_all = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButton_all.setGeometry(QtCore.QRect(10, 40, 91, 31))
        self.pushButton_all.setStyleSheet("border-radius: 15px;\n"
"font: 75 15pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(255, 232, 137);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.527363 rgba(80, 11, 40, 255), stop:1 rgba(187, 23, 43, 255));\n"
"")
        self.pushButton_all.setObjectName("pushButton_all")
        self.pushButton_vip = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButton_vip.setGeometry(QtCore.QRect(350, 40, 91, 31))
        self.pushButton_vip.setStyleSheet("border-radius: 15px;\n"
"border-radius: 15px;\n"
"font: 75 15pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(255, 232, 137);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.527363 rgba(80, 11, 40, 255), stop:1 rgba(187, 23, 43, 255));")
        self.pushButton_vip.setObjectName("pushButton_vip")
        self.pushButton_regular = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButton_regular.setGeometry(QtCore.QRect(460, 40, 101, 31))
        self.pushButton_regular.setStyleSheet("border-radius: 15px;\n"
"border-radius: 15px;\n"
"font: 75 15pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(255, 232, 137);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.527363 rgba(80, 11, 40, 255), stop:1 rgba(187, 23, 43, 255));")
        self.pushButton_regular.setObjectName("pushButton_regular")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(-70, -320, 1361, 331))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:\\KTLT\\HotelManagement\\ui\\../Final_Project/HotelManagement/images/Cover.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.tableWidget_Room.raise_()
        self.pushButton_exit.raise_()
        self.pushButton_checkout.raise_()
        self.dateEdit_date.raise_()
        self.label.raise_()
        self.pushButton_checkin.raise_()
        self.groupBox_3.raise_()
        self.label_3.raise_()
        self.tabWidget.addTab(self.widget, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.tab_7)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 1381, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SFU Toledo")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: qlineargradient(spread:pad, x1:0.054, y1:0.670455, x2:0.587, y2:0.699, stop:0.527363 rgba(161, 196, 253, 255), stop:1 rgba(194, 233, 251, 255));\n"
"font: 75 12pt \"#9Slide03 SFU Toledo Bold\";\n"
"\n"
"border-color: rgb(182, 182, 182);\n"
"font: 57 12pt \"SFU Toledo\";\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBoxType = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.comboBoxType.setGeometry(QtCore.QRect(160, 160, 450, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxType.sizePolicy().hasHeightForWidth())
        self.comboBoxType.setSizePolicy(sizePolicy)
        self.comboBoxType.setMinimumSize(QtCore.QSize(450, 30))
        self.comboBoxType.setMaximumSize(QtCore.QSize(450, 30))
        font = QtGui.QFont()
        font.setFamily("SFU Toledo")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.comboBoxType.setFont(font)
        self.comboBoxType.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.comboBoxType.setObjectName("comboBoxType")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.label_150 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_150.setGeometry(QtCore.QRect(640, 70, 151, 51))
        self.label_150.setStyleSheet("font: 75 12pt \"#9Slide03 SFU Toledo Bold\";\n"
"background-color:transparent")
        self.label_150.setObjectName("label_150")
        self.label_151 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_151.setGeometry(QtCore.QRect(10, 80, 121, 31))
        self.label_151.setStyleSheet("font: 75 12pt \"#9Slide03 SFU Toledo Bold\";\n"
"background-color:transparent")
        self.label_151.setObjectName("label_151")
        self.label_152 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_152.setGeometry(QtCore.QRect(10, 160, 111, 41))
        self.label_152.setStyleSheet("font: 75 12pt \"#9Slide03 SFU Toledo Bold\";\n"
"background-color:transparent")
        self.label_152.setObjectName("label_152")
        self.label_153 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_153.setGeometry(QtCore.QRect(-30, 450, 221, 61))
        self.label_153.setObjectName("label_153")
        self.lineEdit_Rooms_17 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_Rooms_17.setGeometry(QtCore.QRect(220, 460, 281, 31))
        self.lineEdit_Rooms_17.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.lineEdit_Rooms_17.setObjectName("lineEdit_Rooms_17")
        self.label_154 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_154.setGeometry(QtCore.QRect(630, 110, 111, 51))
        self.label_154.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_154.setStyleSheet("font: 75 12pt \"#9Slide03 SFU Toledo Bold\";\n"
"background-color:transparent")
        self.label_154.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_154.setObjectName("label_154")
        self.label_155 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_155.setGeometry(QtCore.QRect(10, 30, 141, 41))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 SFU Toledo Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_155.setFont(font)
        self.label_155.setStyleSheet("font: 75 12pt \"#9Slide03 SFU Toledo Bold\";\n"
"background-color:transparent")
        self.label_155.setObjectName("label_155")
        self.lineEdit_BookingCode = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_BookingCode.setGeometry(QtCore.QRect(160, 40, 450, 30))
        self.lineEdit_BookingCode.setMinimumSize(QtCore.QSize(450, 30))
        self.lineEdit_BookingCode.setMaximumSize(QtCore.QSize(450, 30))
        self.lineEdit_BookingCode.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_BookingCode.setObjectName("lineEdit_BookingCode")
        self.CheckIn = QtWidgets.QDateEdit(parent=self.groupBox_2)
        self.CheckIn.setGeometry(QtCore.QRect(800, 40, 450, 31))
        self.CheckIn.setMinimumSize(QtCore.QSize(450, 30))
        self.CheckIn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.CheckIn.setMaximumDate(QtCore.QDate(9999, 12, 10))
        self.CheckIn.setObjectName("CheckIn")
        self.CheckOut = QtWidgets.QDateEdit(parent=self.groupBox_2)
        self.CheckOut.setGeometry(QtCore.QRect(800, 80, 450, 31))
        self.CheckOut.setMinimumSize(QtCore.QSize(450, 30))
        self.CheckOut.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.CheckOut.setObjectName("CheckOut")
        self.label_156 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_156.setGeometry(QtCore.QRect(10, 120, 111, 31))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 SFU Toledo Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_156.setFont(font)
        self.label_156.setStyleSheet("font: 75 12pt \"#9Slide03 SFU Toledo Bold\";\n"
"background-color:transparent")
        self.label_156.setObjectName("label_156")
        self.lineEdit_Roomname = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_Roomname.setGeometry(QtCore.QRect(160, 80, 450, 30))
        self.lineEdit_Roomname.setMinimumSize(QtCore.QSize(450, 30))
        self.lineEdit_Roomname.setMaximumSize(QtCore.QSize(450, 30))
        self.lineEdit_Roomname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_Roomname.setObjectName("lineEdit_Roomname")
        self.lineEditChildren = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditChildren.setGeometry(QtCore.QRect(800, 120, 450, 30))
        self.lineEditChildren.setMinimumSize(QtCore.QSize(450, 30))
        self.lineEditChildren.setMaximumSize(QtCore.QSize(450, 30))
        self.lineEditChildren.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEditChildren.setObjectName("lineEditChildren")
        self.lineEdit_Roomcode = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_Roomcode.setGeometry(QtCore.QRect(160, 120, 450, 30))
        self.lineEdit_Roomcode.setMinimumSize(QtCore.QSize(450, 30))
        self.lineEdit_Roomcode.setMaximumSize(QtCore.QSize(450, 30))
        self.lineEdit_Roomcode.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_Roomcode.setObjectName("lineEdit_Roomcode")
        self.label_157 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_157.setGeometry(QtCore.QRect(640, 40, 141, 31))
        self.label_157.setStyleSheet("font: 75 12pt \"#9Slide03 SFU Toledo Bold\";\n"
"background-color:transparent")
        self.label_157.setObjectName("label_157")
        self.label_158 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_158.setGeometry(QtCore.QRect(630, 160, 91, 31))
        self.label_158.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_158.setStyleSheet("background-color:transparent;\n"
"font: 75 12pt \"#9Slide03 SFU Toledo Bold\";")
        self.label_158.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_158.setObjectName("label_158")
        self.lineEditAdult = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditAdult.setGeometry(QtCore.QRect(800, 160, 450, 30))
        self.lineEditAdult.setMinimumSize(QtCore.QSize(450, 30))
        self.lineEditAdult.setMaximumSize(QtCore.QSize(450, 30))
        self.lineEditAdult.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEditAdult.setObjectName("lineEditAdult")
        self.pushButton_Save = QtWidgets.QPushButton(parent=self.tab_7)
        self.pushButton_Save.setGeometry(QtCore.QRect(440, 450, 111, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Save.sizePolicy().hasHeightForWidth())
        self.pushButton_Save.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("#9Slide03 SFU Toledo Bold")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setStyleSheet("\n"
"font: 75 15pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(255, 232, 137);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.527363 rgba(80, 11, 40, 255), stop:1 rgba(187, 23, 43, 255));\n"
"    border-radius: 10px;\n"
"")
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.pushButton_Close = QtWidgets.QPushButton(parent=self.tab_7)
        self.pushButton_Close.setGeometry(QtCore.QRect(720, 450, 111, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Close.sizePolicy().hasHeightForWidth())
        self.pushButton_Close.setSizePolicy(sizePolicy)
        self.pushButton_Close.setStyleSheet("\n"
"font: 75 15pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(255, 232, 137);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.527363 rgba(80, 11, 40, 255), stop:1 rgba(187, 23, 43, 255));\n"
"    border-radius: 10px;\n"
"")
        self.pushButton_Close.setObjectName("pushButton_Close")
        self.groupBox_6 = QtWidgets.QGroupBox(parent=self.tab_7)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 210, 1381, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SFU Toledo")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.054, y1:0.670455, x2:0.587, y2:0.699, stop:0.527363 rgba(161, 196, 253, 255), stop:1 rgba(194, 233, 251, 255));\n"
"font: 57 12pt \"SFU Toledo\";\n"
"border-color: rgb(182, 182, 182);\n"
"\n"
"")
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_159 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_159.setGeometry(QtCore.QRect(660, 40, 121, 31))
        self.label_159.setStyleSheet("font: 75 12pt \"#9Slide03 SFU Toledo Bold\";\n"
"background-color: transparent")
        self.label_159.setObjectName("label_159")
        self.label_160 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_160.setGeometry(QtCore.QRect(660, 80, 71, 31))
        self.label_160.setStyleSheet("font: 75 12pt \"#9Slide03 SFU Toledo Bold\";\n"
"background-color: transparent")
        self.label_160.setObjectName("label_160")
        self.label_161 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_161.setGeometry(QtCore.QRect(10, 80, 141, 31))
        self.label_161.setStyleSheet("font: 75 11pt \"#9Slide03 SFU Toledo Bold\";\n"
"background-color: transparent")
        self.label_161.setObjectName("label_161")
        self.label_162 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_162.setGeometry(QtCore.QRect(10, 150, 91, 41))
        self.label_162.setStyleSheet("font: 75 12pt \"#9Slide03 SFU Toledo Bold\";\n"
"background-color: transparent")
        self.label_162.setObjectName("label_162")
        self.label_163 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_163.setGeometry(QtCore.QRect(-30, 450, 221, 61))
        self.label_163.setObjectName("label_163")
        self.lineEdit_Rooms_18 = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.lineEdit_Rooms_18.setGeometry(QtCore.QRect(220, 460, 281, 31))
        self.lineEdit_Rooms_18.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.lineEdit_Rooms_18.setObjectName("lineEdit_Rooms_18")
        self.label_164 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_164.setGeometry(QtCore.QRect(650, 110, 81, 51))
        self.label_164.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_164.setStyleSheet("font: 75 12pt \"#9Slide03 SFU Toledo Bold\";\n"
"background-color: transparent")
        self.label_164.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_164.setObjectName("label_164")
        self.label_165 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_165.setGeometry(QtCore.QRect(10, 40, 141, 31))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 SFU Toledo Bold")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_165.setFont(font)
        self.label_165.setStyleSheet("font: 75 11pt \"#9Slide03 SFU Toledo Bold\";\n"
"background-color: transparent")
        self.label_165.setObjectName("label_165")
        self.lineEdit_Cuscode = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.lineEdit_Cuscode.setGeometry(QtCore.QRect(160, 40, 450, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Cuscode.sizePolicy().hasHeightForWidth())
        self.lineEdit_Cuscode.setSizePolicy(sizePolicy)
        self.lineEdit_Cuscode.setMinimumSize(QtCore.QSize(450, 30))
        self.lineEdit_Cuscode.setMaximumSize(QtCore.QSize(450, 30))
        self.lineEdit_Cuscode.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_Cuscode.setObjectName("lineEdit_Cuscode")
        self.CheckInDateOfBirth = QtWidgets.QDateEdit(parent=self.groupBox_6)
        self.CheckInDateOfBirth.setGeometry(QtCore.QRect(800, 40, 450, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CheckInDateOfBirth.sizePolicy().hasHeightForWidth())
        self.CheckInDateOfBirth.setSizePolicy(sizePolicy)
        self.CheckInDateOfBirth.setMinimumSize(QtCore.QSize(450, 30))
        self.CheckInDateOfBirth.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.CheckInDateOfBirth.setObjectName("CheckInDateOfBirth")
        self.label_166 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_166.setGeometry(QtCore.QRect(-10, 120, 131, 31))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 SFU Toledo Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_166.setFont(font)
        self.label_166.setStyleSheet("font: 75 12pt \"#9Slide03 SFU Toledo Bold\";\n"
"background-color: transparent")
        self.label_166.setObjectName("label_166")
        self.lineEdit_Cusname = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.lineEdit_Cusname.setGeometry(QtCore.QRect(160, 80, 450, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Cusname.sizePolicy().hasHeightForWidth())
        self.lineEdit_Cusname.setSizePolicy(sizePolicy)
        self.lineEdit_Cusname.setMinimumSize(QtCore.QSize(450, 30))
        self.lineEdit_Cusname.setMaximumSize(QtCore.QSize(450, 30))
        self.lineEdit_Cusname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_Cusname.setObjectName("lineEdit_Cusname")
        self.lineEdit_Phone = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.lineEdit_Phone.setGeometry(QtCore.QRect(800, 120, 450, 30))
        self.lineEdit_Phone.setMinimumSize(QtCore.QSize(450, 30))
        self.lineEdit_Phone.setMaximumSize(QtCore.QSize(450, 30))
        self.lineEdit_Phone.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_Phone.setObjectName("lineEdit_Phone")
        self.lineEdit_Identify = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.lineEdit_Identify.setGeometry(QtCore.QRect(160, 120, 450, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Identify.sizePolicy().hasHeightForWidth())
        self.lineEdit_Identify.setSizePolicy(sizePolicy)
        self.lineEdit_Identify.setMinimumSize(QtCore.QSize(450, 30))
        self.lineEdit_Identify.setMaximumSize(QtCore.QSize(450, 30))
        self.lineEdit_Identify.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_Identify.setObjectName("lineEdit_Identify")
        self.label_167 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_167.setGeometry(QtCore.QRect(660, 150, 131, 51))
        self.label_167.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_167.setStyleSheet("font: 75 12pt \"#9Slide03 SFU Toledo Bold\";\n"
"background-color: transparent")
        self.label_167.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_167.setObjectName("label_167")
        self.lineEdit_Requirement = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.lineEdit_Requirement.setGeometry(QtCore.QRect(800, 160, 450, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Requirement.sizePolicy().hasHeightForWidth())
        self.lineEdit_Requirement.setSizePolicy(sizePolicy)
        self.lineEdit_Requirement.setMinimumSize(QtCore.QSize(450, 30))
        self.lineEdit_Requirement.setMaximumSize(QtCore.QSize(450, 30))
        self.lineEdit_Requirement.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_Requirement.setObjectName("lineEdit_Requirement")
        self.comboBoxTypeGender_9 = QtWidgets.QComboBox(parent=self.groupBox_6)
        self.comboBoxTypeGender_9.setGeometry(QtCore.QRect(160, 160, 450, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxTypeGender_9.sizePolicy().hasHeightForWidth())
        self.comboBoxTypeGender_9.setSizePolicy(sizePolicy)
        self.comboBoxTypeGender_9.setMinimumSize(QtCore.QSize(450, 30))
        self.comboBoxTypeGender_9.setMaximumSize(QtCore.QSize(450, 30))
        font = QtGui.QFont()
        font.setFamily("SFU Toledo")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.comboBoxTypeGender_9.setFont(font)
        self.comboBoxTypeGender_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.comboBoxTypeGender_9.setObjectName("comboBoxTypeGender_9")
        self.comboBoxTypeGender_9.addItem("")
        self.comboBoxTypeGender_9.addItem("")
        self.lineEdit_Email = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.lineEdit_Email.setGeometry(QtCore.QRect(800, 80, 450, 30))
        self.lineEdit_Email.setMinimumSize(QtCore.QSize(450, 30))
        self.lineEdit_Email.setMaximumSize(QtCore.QSize(450, 30))
        self.lineEdit_Email.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_Email.setObjectName("lineEdit_Email")
        self.pushButton_Clear = QtWidgets.QPushButton(parent=self.tab_7)
        self.pushButton_Clear.setGeometry(QtCore.QRect(580, 450, 111, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Clear.sizePolicy().hasHeightForWidth())
        self.pushButton_Clear.setSizePolicy(sizePolicy)
        self.pushButton_Clear.setStyleSheet("\n"
"font: 75 15pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(255, 232, 137);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.527363 rgba(80, 11, 40, 255), stop:1 rgba(187, 23, 43, 255));\n"
"    border-radius: 10px;\n"
"")
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.tabWidget.addTab(self.tab_7, "")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, -10, 1281, 321))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("D:\\KTLT\\HotelManagement\\ui\\../images/Cover.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.tabWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "View Booking Details + Search System"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Phone number"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Check-in"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Check-out"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Room type"))
        self.groupBoxCustomerDetails.setTitle(_translate("MainWindow", "Customer Details:"))
        self.label_168.setText(_translate("MainWindow", "Email :"))
        self.label_169.setText(_translate("MainWindow", "Check-in Date :"))
        self.label_170.setText(_translate("MainWindow", "Check-out Date :"))
        self.label_171.setText(_translate("MainWindow", "Room Type :"))
        self.label_172.setText(_translate("MainWindow", "Customer Code:"))
        self.label_173.setText(_translate("MainWindow", "Phone :"))
        self.pushButtonUpdate.setText(_translate("MainWindow", "Update"))
        self.pushButtonDelete.setText(_translate("MainWindow", "Delete"))
        self.pushButtonreset.setText(_translate("MainWindow", "Reset"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "5"))
        self.label_175.setText(_translate("MainWindow", "Name :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Booking Management"))
        self.pushButton_exit.setText(_translate("MainWindow", "EXIT"))
        self.pushButton_checkout.setText(_translate("MainWindow", "CHECK OUT"))
        item = self.tableWidget_Room.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_Room.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_Room.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_Room.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_Room.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_Room.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Room"))
        item = self.tableWidget_Room.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidget_Room.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Customer"))
        item = self.tableWidget_Room.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Type"))
        self.dateEdit_date.setDisplayFormat(_translate("MainWindow", "yyyy/M/d"))
        self.label.setText(_translate("MainWindow", "Date:"))
        self.pushButton_checkin.setText(_translate("MainWindow", "CHECK IN"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Sort"))
        self.pushButton_booked.setText(_translate("MainWindow", "Booked"))
        self.pushButton_vacant.setText(_translate("MainWindow", "Vancant"))
        self.pushButton_all.setText(_translate("MainWindow", "All"))
        self.pushButton_vip.setText(_translate("MainWindow", "VIP"))
        self.pushButton_regular.setText(_translate("MainWindow", "Regular"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "Room Management"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Booking information"))
        self.comboBoxType.setItemText(0, _translate("MainWindow", "VIP"))
        self.comboBoxType.setItemText(1, _translate("MainWindow", "Regular"))
        self.label_150.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Check-out date :</p></body></html>"))
        self.label_151.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Room name :</p></body></html>"))
        self.label_152.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Room type :</p></body></html>"))
        self.label_153.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Rooms:</span></p></body></html>"))
        self.label_154.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Children :</p></body></html>"))
        self.label_155.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Booking code :</p></body></html>"))
        self.CheckIn.setDisplayFormat(_translate("MainWindow", "yyyy/M/d"))
        self.CheckOut.setDisplayFormat(_translate("MainWindow", "yyyy/M/d"))
        self.label_156.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Room code :</p></body></html>"))
        self.label_157.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Check-in date :</p><p align=\"center\"><br/></p></body></html>"))
        self.label_158.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Adult :</p></body></html>"))
        self.pushButton_Save.setText(_translate("MainWindow", "Submit"))
        self.pushButton_Close.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Remove</span></p><p><br/></p></body></html>"))
        self.pushButton_Close.setText(_translate("MainWindow", "Close"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Customer details"))
        self.label_159.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Date of birth :</p></body></html>"))
        self.label_160.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Email :</p></body></html>"))
        self.label_161.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Customer name :</p></body></html>"))
        self.label_162.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Gender :</p></body></html>"))
        self.label_163.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Rooms:</span></p></body></html>"))
        self.label_164.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Phone</p></body></html>"))
        self.label_165.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Customer code :</p></body></html>"))
        self.label_166.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Identity :</p></body></html>"))
        self.label_167.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Requirement:</p></body></html>"))
        self.comboBoxTypeGender_9.setItemText(0, _translate("MainWindow", "Male"))
        self.comboBoxTypeGender_9.setItemText(1, _translate("MainWindow", "Female"))
        self.pushButton_Clear.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Remove</span></p><p><br/></p></body></html>"))
        self.pushButton_Clear.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "New Reservation"))
