# Form implementation generated from reading ui file 'D:\KTLT\HotelManagement\ui\MainWindowRoomManagement.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1023, 742)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget_Room = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget_Room.setGeometry(QtCore.QRect(10, 180, 1001, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_Room.sizePolicy().hasHeightForWidth())
        self.tableWidget_Room.setSizePolicy(sizePolicy)
        self.tableWidget_Room.setMaximumSize(QtCore.QSize(16777215, 411))
        self.tableWidget_Room.setObjectName("tableWidget_Room")
        self.tableWidget_Room.setColumnCount(4)
        self.tableWidget_Room.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Room.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Room.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Room.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Room.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Room.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Room.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Room.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Room.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Room.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Room.setHorizontalHeaderItem(3, item)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 80, 581, 91))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 SFU Toledo Bold")
        font.setPointSize(20)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.pushButton_booked = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_booked.setGeometry(QtCore.QRect(120, 40, 91, 31))
        self.pushButton_booked.setStyleSheet("border-radius: 15px;\n"
"border-radius: 15px;\n"
"font: 75 15pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(255, 232, 137);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.527363 rgba(80, 11, 40, 255), stop:1 rgba(187, 23, 43, 255));")
        self.pushButton_booked.setObjectName("pushButton_booked")
        self.pushButton_vacant = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_vacant.setGeometry(QtCore.QRect(230, 40, 101, 31))
        self.pushButton_vacant.setStyleSheet("border-radius: 15px;\n"
"font: 75 15pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(255, 232, 137);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.527363 rgba(80, 11, 40, 255), stop:1 rgba(187, 23, 43, 255));")
        self.pushButton_vacant.setObjectName("pushButton_vacant")
        self.pushButton_all = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_all.setGeometry(QtCore.QRect(10, 40, 91, 31))
        self.pushButton_all.setStyleSheet("border-radius: 15px;\n"
"font: 75 15pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(255, 232, 137);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.527363 rgba(80, 11, 40, 255), stop:1 rgba(187, 23, 43, 255));\n"
"")
        self.pushButton_all.setObjectName("pushButton_all")
        self.pushButton_vip = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_vip.setGeometry(QtCore.QRect(350, 40, 91, 31))
        self.pushButton_vip.setStyleSheet("border-radius: 15px;\n"
"border-radius: 15px;\n"
"font: 75 15pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(255, 232, 137);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.527363 rgba(80, 11, 40, 255), stop:1 rgba(187, 23, 43, 255));")
        self.pushButton_vip.setObjectName("pushButton_vip")
        self.pushButton_regular = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_regular.setGeometry(QtCore.QRect(460, 40, 91, 31))
        self.pushButton_regular.setStyleSheet("border-radius: 15px;\n"
"border-radius: 15px;\n"
"font: 75 15pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(255, 232, 137);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.527363 rgba(80, 11, 40, 255), stop:1 rgba(187, 23, 43, 255));")
        self.pushButton_regular.setObjectName("pushButton_regular")
        self.pushButton_checkin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_checkin.setGeometry(QtCore.QRect(270, 610, 141, 51))
        self.pushButton_checkin.setStyleSheet("border-radius: 15px;\n"
"font: 75 15pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(255, 232, 137);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.527363 rgba(80, 11, 40, 255), stop:1 rgba(187, 23, 43, 255));\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/DUYEN/Downloads/Tick.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_checkin.setIcon(icon)
        self.pushButton_checkin.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_checkin.setObjectName("pushButton_checkin")
        self.pushButton_checkout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_checkout.setGeometry(QtCore.QRect(430, 610, 151, 51))
        self.pushButton_checkout.setStyleSheet("border-radius: 15px;\n"
"font: 75 15pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(255, 232, 137);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.527363 rgba(80, 11, 40, 255), stop:1 rgba(187, 23, 43, 255));\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/DUYEN/Downloads/187510.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_checkout.setIcon(icon1)
        self.pushButton_checkout.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_checkout.setObjectName("pushButton_checkout")
        self.pushButton_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(600, 610, 131, 51))
        self.pushButton_exit.setStyleSheet("border-radius: 15px;\n"
"font: 75 15pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(255, 232, 137);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.527363 rgba(80, 11, 40, 255), stop:1 rgba(187, 23, 43, 255));\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/TranHieuKieuDuyen_K244111457_K24411E/Midterm_TranHieuKieuDuyen/WarehouseManagement/images/close.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_exit.setIcon(icon2)
        self.pushButton_exit.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(660, 120, 71, 31))
        self.label.setStyleSheet("font: 75 20pt \"#9Slide03 SFU Toledo Bold\";\n"
"color: rgb(0, 0, 0);\n"
"\n"
"")
        self.label.setObjectName("label")
        self.dateEdit_date = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateEdit_date.setGeometry(QtCore.QRect(730, 120, 271, 31))
        self.dateEdit_date.setObjectName("dateEdit_date")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1023, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_exit.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget_Room.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_Room.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_Room.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_Room.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_Room.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_Room.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Room"))
        item = self.tableWidget_Room.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidget_Room.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Customer"))
        item = self.tableWidget_Room.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Type"))
        self.groupBox.setTitle(_translate("MainWindow", "Sort"))
        self.pushButton_booked.setText(_translate("MainWindow", "Booked"))
        self.pushButton_vacant.setText(_translate("MainWindow", "Vancant"))
        self.pushButton_all.setText(_translate("MainWindow", "All"))
        self.pushButton_vip.setText(_translate("MainWindow", "VIP"))
        self.pushButton_regular.setText(_translate("MainWindow", "Regular"))
        self.pushButton_checkin.setText(_translate("MainWindow", "CHECK IN"))
        self.pushButton_checkout.setText(_translate("MainWindow", "CHECK OUT"))
        self.pushButton_exit.setText(_translate("MainWindow", "EXIT"))
        self.label.setText(_translate("MainWindow", "Date:"))
